project: default
source:
  repoURL: 'https://github.com/ranjana990/lambda2.git'
  path: .
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}
