apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'Booking'
project: ''
source:
  repoURL: 'https://github.com/ranjana990/lambda2.git'
  path: .
  targetRevision: HEAD
helm:
   version: 3
   values: 
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
  name: ''
syncPolicy:
  automated: {}
